# Site settings
title: iainjmitchell
email: iainjmitchell@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  The website of iainjmitchell, a Software Practitioner from Manchester UK.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://iainjmitchell.com" # the base hostname & protocol for your site
twitter_username: iainjmitchell
github_username:  iainjmitchell
permalink: /blog/:title
exclude: ["gems"]

# Build settings
markdown: kramdown
gems:
  - jekyll-redirect-from
sass:
    style: compressed
